In [2]:
import pandas as pd

df =pd.read_csv('red_30_tech_us_sales.csv')

print(df.head())

      EmpID   OrderNum  OrderDate  OrderType  Quantity     Price   Discount   \
0  900015476   1100948   9/3/2017     Retail         1    $44.95          0
1  900015476   1101096  9/24/2017  Wholesale        10     $4.99      $1.00
2  900015476   1101138  10/1/2017  Wholesale         4   $250.00     $50.00
3  900015476   1101158  10/3/2017     Retail         1   $250.00          0
4  900015476   1101181  10/9/2017     Retail         1    $13.99          0

   Order Total
0       $44.95
1       $48.90
2      $950.00
3      $250.00
4       $13.99

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4976 entries, 0 to 4975
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   EmpID          4976 non-null   int64
 1   OrderNum       4976 non-null   int64
 2   OrderDate      4976 non-null   object
 3   OrderType      4976 non-null   object
 4   Quantity       4976 non-null   int64
 5    Price         4976 non-null   object
 6    Discount      4976 non-null   object
 7    Order Total   4976 non-null   object
dtypes: int64(3), object(5)
memory usage: 311.1+ KB

In [4]:
df['OrderNum']

0       1100948
1       1101096
2       1101138
3       1101158
4       1101181
         ...
4971    1105360
4972    1105451
4973    1105501
4974    1105748
4975    1105834
Name: OrderNum, Length: 4976, dtype: int64

In [6]:
df[df['Quantity']> 10]

,EmpID,OrderNum,OrderDate,OrderType,Quantity,Price,Discount,Order Total
7,900015476,1101495,11/22/2017,Wholesale,13,$899.00,$179.80,"$11,507.20"
17,900015476,1102227,3/9/2018,Wholesale,15,$13.99,$2.80,$207.05
29,900015476,1103219,7/27/2018,Wholesale,53,$69.00,$13.80,"$3,643.20"
38,900015476,1103799,10/18/2018,Wholesale,78,$44.95,$8.99,"$3,497.11"
51,900015476,1104837,3/23/2019,Wholesale,13,$89.00,$17.80,"$1,139.20"
...,...,...,...,...,...,...,...,...
4969,900011189,1105229,5/21/2019,Wholesale,83,$32.95,$6.59,"$2,728.26"
4972,900011189,1105451,6/20/2019,Wholesale,69,$450.00,$90.00,"$30,960.00"
4973,900011189,1105501,6/28/2019,Wholesale,11,$28.99,$5.80,$313.09
4974,900011189,1105748,8/7/2019,Wholesale,11,$119.00,$23.80,"$1,285.20"
4975,900011189,1105834,8/18/2019,Wholesale,67,$42.99,$8.60,"$2,871.73"

In [10]:
df[(df['Quantity']>10) & (df['OrderType']!= "Wholesale")]

,EmpID,OrderNum,OrderDate,OrderType,Quantity,Price,Discount,Order Total
119,900019884,1104570,2/14/2019,Retail,60,$450.00,0,"$27,000.00"
210,900018190,1101368,11/2/2017,Retail,48,$49.00,0,"$2,352.00"
549,900010405,1105819,8/16/2019,Retail,16,$8.99,0,$143.84
574,900014598,1101646,12/12/2017,Retail,12,$179.00,0,"$2,148.00"
598,900014598,1102372,4/1/2018,Retail,13,$19.99,0,$259.87
645,900014598,1103986,11/16/2018,Retail,87,$899.00,0,"$78,213.00"
653,900014598,1104229,12/21/2018,Retail,41,$29.99,0,"$1,229.59"
748,900014032,1103375,8/17/2018,Retail,46,$37.99,0,"$1,747.54"
788,900014032,1105860,8/22/2019,Retail,68,$49.95,0,"$3,396.60"
1021,900012972,1104668,2/27/2019,Retail,12,$189.00,0,"$2,268.00"
1071,900012260,1102471,4/15/2018,Retail,31,$19.50,0,$604.50
1135,900019833,1102082,2/16/2018,Retail,109,$23.99,0,"$2,614.91"
1218,900014980,1100983,9/8/2017,Retail,24,$23.99,0,$575.76
1312,900014980,1105080,4/26/2019,Retail,76,$395.00,0,"$30,020.00"
1416,900013598,1105680,7/26/2019,Retail,92,$14.99,0,"$1,379.08"
1441,900018996,1102270,3/15/2018,Retail,17,$499.00,0,"$8,483.00"
1503,900018996,1105040,4/20/2019,Retail,98,$13.99,0,"$1,371.02"
1779,900012326,1104114,12/7/2018,Retail,18,$19.50,0,$351.00
1812,900012326,1105430,6/17/2019,Retail,76,$49.95,0,"$3,796.20"
1880,900012483,1103886,11/2/2018,Retail,40,$20.95,0,$838.00
1907,900012483,1104825,3/20/2019,Retail,54,$399.00,0,"$21,546.00"
1916,900012483,1105296,5/29/2019,Retail,91,$89.00,0,"$8,099.00"
1982,900010875,1103759,10/13/2018,Retail,77,$13.99,0,"$1,077.23"
2051,900010836,1101762,12/29/2017,Retail,14,$899.00,0,"$12,586.00"
2089,900010836,1103150,7/18/2018,Retail,13,$214.00,0,"$2,782.00"
2090,900010836,1103175,7/21/2018,Retail,75,$29.99,0,"$2,249.25"
2121,900010836,1104280,12/27/2018,Retail,108,$49.00,0,"$5,292.00"
2410,900012723,1102472,4/15/2018,Retail,92,$12.99,0,"$1,195.08"
2448,900012723,1103146,7/17/2018,Retail,68,$8.99,0,$611.32
2825,900019978,1101064,9/19/2017,Retail,85,$89.00,0,"$7,565.00"
2895,900015938,1101102,9/25/2017,Retail,60,$24.95,0,"$1,497.00"
2951,900015938,1102516,4/22/2018,Retail,13,$189.00,0,"$2,457.00"
2981,900015938,1103231,7/29/2018,Retail,13,$9.99,0,$129.87
3014,900015938,1104067,11/30/2018,Retail,92,$549.00,0,"$50,508.00"
3028,900015938,1104296,12/29/2018,Retail,49,$12.00,0,$588.00
3033,900015938,1104413,1/18/2019,Retail,98,$250.00,0,"$24,500.00"
3122,900010430,1102174,3/2/2018,Retail,91,$245.00,0,"$22,295.00"
3178,900010430,1104192,12/17/2018,Retail,54,$16.99,0,$917.46
3205,900010430,1105195,5/15/2019,Retail,43,$245.00,0,"$10,535.00"
3235,900016297,1101507,11/24/2017,Retail,44,$4.99,0,$219.56
3270,900016297,1102571,5/1/2018,Retail,13,$699.00,0,"$9,087.00"
3287,900016297,1103127,7/16/2018,Retail,37,$19.50,0,$721.50
3388,900015082,1101830,1/8/2018,Retail,93,$499.00,0,"$46,407.00"
3548,900017930,1103154,7/18/2018,Retail,53,$19.50,0,"$1,033.50"
3569,900017930,1104517,2/6/2019,Retail,60,$27.50,0,"$1,650.00"
3818,900013626,1103359,8/14/2018,Retail,32,$49.00,0,"$1,568.00"
3843,900013626,1103919,11/6/2018,Retail,13,$69.00,0,$897.00
3971,900013387,1101969,1/30/2018,Retail,74,$19.50,0,"$1,443.00"
3985,900013387,1102336,3/26/2018,Retail,40,$189.00,0,"$7,560.00"
4096,900017044,1101570,12/2/2017,Retail,58,$15.50,0,$899.00
4110,900017044,1102650,5/11/2018,Retail,99,$13.99,0,"$1,385.01"
4215,900012258,1105488,6/26/2019,Retail,37,$11.99,0,$443.63
4281,900015673,1105404,6/13/2019,Retail,94,$23.99,0,"$2,255.06"
4286,900015673,1105908,8/29/2019,Retail,64,$179.00,0,"$11,456.00"
4613,900016602,1105090,4/27/2019,Retail,51,$17.50,0,$892.50
4821,900018460,1104241,12/23/2018,Retail,78,$119.00,0,"$9,282.00"
4835,900018460,1104752,3/11/2019,Retail,29,$32.95,0,$955.55
4945,900011189,1103315,8/9/2018,Retail,77,$12.00,0,$924.00

In [11]:
df.dtypes

EmpID             int64
OrderNum          int64
OrderDate        object
OrderType        object
Quantity          int64
 Price           object
 Discount        object
 Order Total     object
dtype: object

In [44]:
unique_ids = pd.Series(df['EmpID '].unique())

print(unique_ids)

0     900015476
1     900019884
2     900012297
3     900018190
4     900010405
5     900014598
6     900014032
7     900012180
8     900012972
9     900012260
10    900019833
11    900014980
12    900013598
13    900018996
14    900016416
15    900012326
16    900012483
17    900010875
18    900010836
19    900018661
20    900012723
21    900019311
22    900018689
23    900019978
24    900015938
25    900010430
26    900016297
27    900015082
28    900017930
29    900016088
30    900013626
31    900013387
32    900017044
33    900012258
34    900015673
35    900011056
36    900019250
37    900016392
38    900013587
39    900016602
40    900011678
41    900018460
42    900010813
43    900011189
dtype: int64